# -*- coding: utf-8 -*-
#
# sample documentation build configuration file, created by
# sphinx-quickstart on Mon Apr 16 21:22:43 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute.
# Example:
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings.
# They can be extensions coming with Sphinx (named 'sphinx.ext.*')
# or your custom ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'sample'
copyright = u'2012, Kenneth Reitz'

# The short X.Y version.
version = 'v0.0.1'
# The full version, including alpha/beta/rc tags.
release = 'v0.0.1'

# List of patterns to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'default'

# Add any paths that contain custom static files here.
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'sampledoc'

# -- Options for LaTeX output --------------------------------------------------

latex_documents = [
    ('index', 'sample.tex', u'sample Documentation',
     u'Kenneth Reitz', 'manual'),
]

# -- Options for manual page output --------------------------------------------

man_pages = [
    ('index', 'sample', u'sample Documentation',
     [u'Kenneth Reitz'], 1)
]

# -- Options for Texinfo output ------------------------------------------------

texinfo_documents = [
    ('index', 'sample', u'sample Documentation',
     u'Kenneth Reitz', 'sample', 'One line description of project.',
     'Miscellaneous'),
]
